### ISSUE TITLE
not open in browser after answer the question from search result

### ISSUE THREAD

**Issue by sugizo** [SomedudeX/vidsrc-search#2]
**problem**
not open in browser 
after answer the question 
from search result

**expected result**
automatically open in browser (new tab or new brower window) 
after answer the question 
from search result

**current work around**
user must click the url shown 
on url column 
from search result

**info**
- env where vidsrc-search installed : google colab
- os on google colab : ubuntu jammy x86_64
- brower used when open google colab : google chrome
- user os : win 11

**trial 1st just hit enter on last question**
```
 > Choose an index to open in browser: 1

 [Warning] The content of the movie is hosted on a third party site. The
           site is not endorsed by the author or checked for its quality, 
           content, or authenticity. The author of vidsrc-search disclaims
           any responsibility, express or implied, of the consequences 
           as a result your usage or dependence on the website provided 
           through this tool. 
 [Warning] The following window shown will be the contents of vidsrc.to

 > I have read and understood the conditions above (Y/n) 
```

**trial 2nd**
 ```
> Choose an index to open in browser: 1

 [Warning] The content of the movie is hosted on a third party site. The
           site is not endorsed by the author or checked for its quality, 
           content, or authenticity. The author of vidsrc-search disclaims
           any responsibility, express or implied, of the consequences 
           as a result your usage or dependence on the website provided 
           through this tool. 
 [Warning] The following window shown will be the contents of vidsrc.to

 > I have read and understood the conditions above (Y/n) Y

 [Info] Verifying internet connection
 [Info] Testing connection by pinging google.com
 [Info] Testing connection by pinging vidsrc.to

 [Info] Checking for local cache
 [Info] Local cache not found: Getting remote html
 [Info] Remote html request status code is 200
 [Info] Writing remote html content to local cache
 [Info] Opening #1 'Steinheist (2022)' in new browser window
```

best regards

**Comment by SomedudeX** [comment]
Are you running vidsrc-search on Google Colab? 

If so, not much can be done about this issue. Because Python is running on a remote server, it can only access the services and apis that the server provides and allows. So unless Google Colab has an api that allows Python to remotely control the connected browser, getting a local browser tab open while running on Google Colab is not possible. 

What probably happened after you opened an entry is that Python attempted to open the default browser on the Google Colab server. This obviously resulted in nothing, since there is probably no browser install on the Google Colab server, which is why nothing happened. 

If you would like vidsrc-search automatically opening a browser after selecting an entry, try running it on the machine that you'd like to see the browser opened on (e.g. locally).

**Comment by sugizo** [comment]
> Are you running vidsrc-search on Google Colab?

yes, loud and clear explanation, 
thank you
